version: '3.1'

services:
  passport:
    image: "passport"
    container_name: passport
    ports:
      - "9000:9000"
    volumes:
      - "./data/conf:/data/conf"
    networks:
      - default-net

networks:
  default-net:
    external:
      name: dev_bridge
